version: '3.3'

services:
    app:
        image: auful/kuisapp-app:latest
        container_name: app
        restart: unless-stopped
        tty: true
        depends_on:
            - cache
        networks:
            - app-network

    web_server:
        image: auful/kuisapp-webserver:latest
        container_name: web_server
        restart: unless-stopped
        tty: true
        ports:
            - "8003:80"
        depends_on:
            - app
        networks:
            - app-network

mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
        - ./run/var:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=securerootpassword
        - MYSQL_DATABASE=${{secrets.DB_DATABASE}}
        - MYSQL_USER=${{secrets.DB_USERNAME}}
        - MYSQL_PASSWORD=${{secrets.DB_PASSWORD}}
    networks:
        backend:
            aliases:
                - mysql-db

networks:
    backend:
        name: backend-network
