version: '3.5'

services:
    app:
        image: auful/kuisapp:latest
        container_name: app
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            backend:
                aliases:
                    - app

    web_server:
        image: auful/kuisapp:latest
        container_name: web_server
        restart: unless-stopped
        tty: true
        ports:
            - "8003:80"
        depends_on:
            - app
        networks:
            - app-network

    mysql-db:
        image: mysql:5.7
        container_name: mysql-db
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
        networks:
            backend:
                aliases:
                    - mysql-db

networks:
    backend:
        name: backend-network
